In [1]:
import numpy as np

In [4]:
# grid of 16x16 in [0,2*pi]x[0,2*pi]
x = np.linspace(0, 2*np.pi, 16, endpoint=False)
y = np.linspace(0, 2*np.pi, 16, endpoint=False)
X, Y = np.meshgrid(x, y)


In [5]:
np.sin(X) + np.sin(Y) + np.sin(X+Y)

array([[ 0.00000000e+00,  7.65366865e-01,  1.41421356e+00,
         1.84775907e+00,  2.00000000e+00,  1.84775907e+00,
         1.41421356e+00,  7.65366865e-01,  2.44929360e-16,
        -7.65366865e-01, -1.41421356e+00, -1.84775907e+00,
        -2.00000000e+00, -1.84775907e+00, -1.41421356e+00,
        -7.65366865e-01],
       [ 7.65366865e-01,  1.47247365e+00,  2.01366975e+00,
         2.30656296e+00,  2.30656296e+00,  2.01366975e+00,
         1.47247365e+00,  7.65366865e-01,  2.22044605e-16,
        -7.07106781e-01, -1.24830288e+00, -1.54119610e+00,
        -1.54119610e+00, -1.24830288e+00, -7.07106781e-01,
        -8.55552023e-16],
       [ 1.41421356e+00,  2.01366975e+00,  2.41421356e+00,
         2.55486585e+00,  2.41421356e+00,  2.01366975e+00,
         1.41421356e+00,  7.07106781e-01,  1.11022302e-16,
        -5.99456184e-01, -1.00000000e+00, -1.14065228e+00,
        -1.00000000e+00, -5.99456184e-01, -4.66973965e-16,
         7.07106781e-01],
       [ 1.84775907e+00,  2.30656296e

In [9]:
np.cos(X) + np.cos(X+Y)

array([[ 2.00000000e+00,  1.84775907e+00,  1.41421356e+00,
         7.65366865e-01,  1.22464680e-16, -7.65366865e-01,
        -1.41421356e+00, -1.84775907e+00, -2.00000000e+00,
        -1.84775907e+00, -1.41421356e+00, -7.65366865e-01,
        -3.67394040e-16,  7.65366865e-01,  1.41421356e+00,
         1.84775907e+00],
       [ 1.92387953e+00,  1.63098631e+00,  1.08979021e+00,
         3.82683432e-01, -3.82683432e-01, -1.08979021e+00,
        -1.63098631e+00, -1.92387953e+00, -1.92387953e+00,
        -1.63098631e+00, -1.08979021e+00, -3.82683432e-01,
         3.82683432e-01,  1.08979021e+00,  1.63098631e+00,
         1.92387953e+00],
       [ 1.70710678e+00,  1.30656296e+00,  7.07106781e-01,
         1.11022302e-16, -7.07106781e-01, -1.30656296e+00,
        -1.70710678e+00, -1.84775907e+00, -1.70710678e+00,
        -1.30656296e+00, -7.07106781e-01, -1.16573418e-15,
         7.07106781e-01,  1.30656296e+00,  1.70710678e+00,
         1.84775907e+00],
       [ 1.38268343e+00,  9.23879533e

In [7]:
np.cos(Y) + np.cos(X+Y)

array([[ 2.00000000e+00,  1.92387953e+00,  1.70710678e+00,
         1.38268343e+00,  1.00000000e+00,  6.17316568e-01,
         2.92893219e-01,  7.61204675e-02,  0.00000000e+00,
         7.61204675e-02,  2.92893219e-01,  6.17316568e-01,
         1.00000000e+00,  1.38268343e+00,  1.70710678e+00,
         1.92387953e+00],
       [ 1.84775907e+00,  1.63098631e+00,  1.30656296e+00,
         9.23879533e-01,  5.41196100e-01,  2.16772751e-01,
         0.00000000e+00, -7.61204675e-02, -1.11022302e-16,
         2.16772751e-01,  5.41196100e-01,  9.23879533e-01,
         1.30656296e+00,  1.63098631e+00,  1.84775907e+00,
         1.92387953e+00],
       [ 1.41421356e+00,  1.08979021e+00,  7.07106781e-01,
         3.24423349e-01,  1.11022302e-16, -2.16772751e-01,
        -2.92893219e-01, -2.16772751e-01, -1.11022302e-16,
         3.24423349e-01,  7.07106781e-01,  1.08979021e+00,
         1.41421356e+00,  1.63098631e+00,  1.70710678e+00,
         1.63098631e+00],
       [ 7.65366865e-01,  3.82683432e